[2024-01-31T15:50:36.289+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: vulnerability_email_notification.process_vulnerability_data manual__2024-01-31T15:50:35.603426+00:00 [queued]>
[2024-01-31T15:50:36.297+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: vulnerability_email_notification.process_vulnerability_data manual__2024-01-31T15:50:35.603426+00:00 [queued]>
[2024-01-31T15:50:36.298+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-01-31T15:50:36.311+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): process_vulnerability_data> on 2024-01-31 15:50:35.603426+00:00
[2024-01-31T15:50:36.315+0000] {standard_task_runner.py:60} INFO - Started process 17652 to run task
[2024-01-31T15:50:36.317+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'vulnerability_email_notification', 'process_vulnerability_data', 'manual__2024-01-31T15:50:35.603426+00:00', '--job-id', '51', '--raw', '--subdir', 'DAGS_FOLDER/cvd_mail_and_reschedule.py', '--cfg-path', '/tmp/tmpphfd58mw']
[2024-01-31T15:50:36.319+0000] {standard_task_runner.py:88} INFO - Job 51: Subtask process_vulnerability_data
[2024-01-31T15:50:36.356+0000] {task_command.py:423} INFO - Running <TaskInstance: vulnerability_email_notification.process_vulnerability_data manual__2024-01-31T15:50:35.603426+00:00 [running]> on host 8d8bbdf320cd
[2024-01-31T15:50:36.426+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='vulnerability_email_notification' AIRFLOW_CTX_TASK_ID='process_vulnerability_data' AIRFLOW_CTX_EXECUTION_DATE='2024-01-31T15:50:35.603426+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-01-31T15:50:35.603426+00:00'
[2024-01-31T15:50:36.427+0000] {cvd_mail_and_reschedule.py:63} INFO - SMTP server connecting...
[2024-01-31T15:50:36.430+0000] {cvd_mail_and_reschedule.py:70} INFO - SMTP server connected successfully.
[2024-01-31T15:50:36.440+0000] {cvd_mail_and_reschedule.py:81} INFO - JSON data loaded successfully.
[2024-01-31T15:50:36.452+0000] {cvd_mail_and_reschedule.py:106} INFO - Email sent to abuse@amazonaws.com
[2024-01-31T15:50:36.458+0000] {cvd_mail_and_reschedule.py:106} INFO - Email sent to abuse@amazonaws.com
[2024-01-31T15:50:36.465+0000] {cvd_mail_and_reschedule.py:106} INFO - Email sent to abuse@amazonaws.com
[2024-01-31T15:50:36.471+0000] {cvd_mail_and_reschedule.py:106} INFO - Email sent to abuse@amazonaws.com
[2024-01-31T15:50:36.473+0000] {cvd_mail_and_reschedule.py:113} INFO - SMTP server connection closed successfully.
[2024-01-31T15:50:36.473+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-01-31T15:50:36.482+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=vulnerability_email_notification, task_id=process_vulnerability_data, execution_date=20240131T155035, start_date=20240131T155036, end_date=20240131T155036
[2024-01-31T15:50:36.530+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-01-31T15:50:36.546+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
